import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import { TranslationsProvider } from "@/lib/i18n/translation-context";
import { getDictionary } from "@/lib/i18n/get-dictionary";
import type { AppLocale } from "@/lib/i18n/config";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: AppLocale };
}) {
  const messages = await getDictionary(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <TranslationsProvider locale={locale} messages={messages}>
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
